name: Hello World

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]


jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hello, World!"
